# Generated by Django 5.2.2 on 2025-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображение мест'},
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='position',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
