# Generated by Django 5.2.2 on 2025-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placeimage_options_remove_placeimage_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения мест'},
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='order',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
