# Generated by Django 5.2.2 on 2025-10-24 17:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options_remove_placeimage_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
